{% set name = "sentinelhub" %}
{% set version = "2.6.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "94b1ff8402291683a801ae6293a3982360b9b7d90657293c04e16edb55a7ed10"

build:
  number: 0
  entry_points:
    - sentinelhub=sentinelhub.commands:main_help
    - sentinelhub.aws=sentinelhub.commands:aws
    - sentinelhub.config=sentinelhub.commands:config
    - sentinelhub.download=sentinelhub.commands:download
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: true  # [py<32]

requirements:
  host:
    - boto3
    - botocore
    - click
    - numpy
    - pillow
    - pip
    - pyproj
    - python
    - python-dateutil
    - requests
    - shapely
    - tifffile
    - utm
    - wheel
  run:
    - boto3
    - botocore
    - click
    - numpy
    - pillow
    - pyproj
    - python
    - python-dateutil
    - requests
    - shapely
    - tifffile
    - utm
    - wheel

test:
  imports:
    - sentinelhub
  commands:
    - sentinelhub --help
    - sentinelhub.aws --help
    - sentinelhub.config --help
    - sentinelhub.download --help

about:
  home: "https://github.com/sentinel-hub/sentinelhub-py"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.md"
  summary: "Sentinel Hub Utilities: skeleton by Thingus"
  doc_url: "https://sentinelhub-py.readthedocs.io/en/latest/"
  dev_url: "https://github.com/sentinel-hub/sentinelhub-py"

extra:
  recipe-maintainers:
    - Thingus
    - AlecksMat
    - andrejburja
    - iovson
