{% set name = "html2text" %}
{% set version = "2018.1.9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "627514fb30e7566b37be6900df26c2c78a030cc9e6211bda604d8181233bcdd4"

build:
  number: 0
  entry_points:
    - html2text=html2text.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: true  # [py<32]

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - html2text
  commands:
    - html2text --help

about:
  home: "https://github.com/Alir3z4/html2text/"
  license: "GNU General Public (GPL)"
  license_family: "LGPL"
  license_file: "COPYING"
  summary: "Turn HTML into equivalent Markdown-structured text. Skeleton by Thingus as dependency for Pyeo."
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - Thingus
