{% set name = "sentinelsat" %}
{% set version = "0.13" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "a4ffd5d17b4a57928bb95104a0405f5de4c1d5dd00571023c3af97037ea18440"

build:
  number: 0
  entry_points:
    - sentinelsat=sentinelsat.scripts.cli:cli
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  skip: true  # [py<32]
  

requirements:
  host:
    - click
    - geojson >=2
    - geomet
    - html2text
    - pip
    - python
    - requests
    - six
    - tqdm
  run:
    - click
    - geojson >=2
    - geomet
    - html2text
    - python
    - requests
    - six
    - tqdm

test:
  imports:
    - sentinelsat
    - sentinelsat.scripts
  commands:
    - sentinelsat --help

about:
  home: "https://github.com/sentinelsat/sentinelsat"
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: "GPL3"
  license_file: "LICENSE"
  summary: "Utility to search and download Copernicus Sentinel satellite images. Skeleton generated by Thingus"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - Thingus 
