{% set name = "pyeo" %}
{% set version = "0.65" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/clcr/pyeo/archive/v0.65-alpha.tar.gz
  sha256: c759301d6669e5e3a1ac182a9976436a2b1093ccd553ffaa2921901c115b55e3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win]
  skip: true  # [py<32]

requirements:
  build:
    - python
    - pip
  host:
    - python
    - pip
  run:
    - boto3
    - botocore
    - gdal
    - joblib
    - matplotlib
    - pip
    - pytest
    - python
    - requests
    - scikit-image
    - setuptools
    - numpy
    - scikit-learn=0.19.2=py36h4989274_0
    - scipy
    - python-fmask
    - geojson
    - sentinelhub
    - sentinelsat
    - tenacity
    - tqdm

test:
  imports:
    - pyeo
    - pyeo.tests
  requires:
    - pytest
  commands:
    - python -m pytest pyeo/tests/test_imports.py

about:
  home: http://github.com/clcr/pyeo
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'End-to-end Python processing of visible satellite images'

  description:
    A Python package based on GDAL, Numpy and Scikit-learn for end-to-end processing
    of satellite images
  doc_url: https://clcr.github.io/pyeo/build/html/index.html
  dev_url: https://github.com/clcr/pyeo

extra:
  recipe-maintainers:
    - thingus
